language: node_js
node_js:
- 0.1
env:
  global:
  - secure: MlahmsOy62rJRenjUQdOQhEc7nss5pa8rbbHww/FiB7QxD+LZIBCZvkRoHwcgkwfP7UG9uHOpwWvTwrtMpfzeT6+WVdAWVlK9bTeE2AUqaZcOq8M6qucTBkD18Rm5WgrdD2jf7FYxq48FCNrs+wRK9ETePByDwSL0k3rhd5w+Hs=
  - secure: XObIUPHNHoQ6DcCNnizAOFxbhIXCwWFg8/pFe1VvUMGuShhPyrV+l5V0lw0ZLO3iWYGmXDv8Fh4usfLgRBs97lwx4xEfFtln9IbMGDe+NNq/u4fWYAwIYSkT4iNOpES96O0csXot8qbuvZMR1yG4odmTcMxahc9vzUFQeCGUvKI=
before_script:
- npm install component component-stylus git+https://github.com/mvanasse/saucer
- component install
- component build --standalone shoelace-modal --use component-stylus
script: saucer test
